### ISSUE TITLE
Support the SQL version

### ISSUE THREAD

**Issue by zedtux** [juliogarciag/atom-rails-model-schema#25]
Given a Rails project using an sql file instead of the `schema.rb`, the package should be able to show the panel.

A convention should be defined in order to name the sql file so that the package could find it easily.
Then updating the [schema-content.coffee](https://github.com/juliogarciag/atom-rails-model-schema/blob/master/lib/schema-content.coffee#L44) in order to no more check for `create_table` but `CREATE TABLE` should do the trick.

**Comment by zedtux** [comment]
@juliogarciag are you maintaining this project?

**Comment by juliogarciag** [comment]
Not really. This package was built in a time where some atom apis where unstable, I haven't planned it well, and I also used text parsing which can't never give me the source of turth. I just actually started a rewrite that asks for the state of the models to Rails itself using `bin/rails runner /path/to/script/in/the/package.rb`: https://atom.io/packages/rails-atom-schema

It's not perfect yet and I only tested it with Rbenv installations (I don't know if it works with rvm or chruby yet, but if you find you can't you can create an issue). Also, because it asks to Rails itself, the Ruby code doesn't need to parse anything because it already has the columns loaded regardless of the type of schema used.

Can you give it a try? I'm planning on adding a banner to this package to deprecate it after I find the other package is stable enough.

**Comment by zedtux** [comment]
Well that's kind of a good news 👍 

I need to check as I'm using ruby in Docker but I will give it a try.

**Comment by zedtux** [comment]
Thank you @juliogarciag for this update, I'm closing this issue then.
